///////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2026 Jean-Philippe Steinmetz
// SPDX-License-Identifier: MPL-2.0
///////////////////////////////////////////////////////////////////////////////
import { ObjectDecorators } from "@rapidrest/core";
import {
    DEFAULT_CSRF_COOKIE_NAME,
    buildCsrfCookie,
    generateCsrfToken,
    type HttpResponse,
} from "@rapidrest/service-core";

const { Config } = ObjectDecorators;

/**
 * Configuration options controlling the CSRF cookie `CsrfUtils` writes alongside the `jwt`/`refresh`
 * cookies `TokenUtils` issues.
 */
export interface CsrfCookieConfig {
    /**
     * Set to `true` to rotate the CSRF cookie at every point `TokenUtils` issues or clears the `jwt`/
     * `refresh` cookies (login, refresh, elevation, logout). Default `false`, matching `TokenUtils`'
     * own `auth:cookie.enabled` default: a CSRF cookie only matters once `jwt`/`refresh` are
     * themselves issued as cookies in the first place.
     *
     * Rotation here is defense-in-depth, not the only way a caller ever gets this cookie —
     * `@rapidrest/service-core`'s `RouteUtils.checkCsrf()` also lazily issues one on any request that
     * doesn't already have it (see that module's doc comment), which is what lets a caller who signed
     * in before this was enabled, or a service that never goes through `TokenUtils` at all (e.g.
     * `server`/`restapi`), still end up with a valid cookie. What rotation buys on top of that: a
     * fresh, unguessable token at every privilege change (login, elevation) instead of carrying the
     * same value across a session indefinitely.
     */
    enabled?: boolean;
    /** The cookie's name. Default `"csrf"` (`DEFAULT_CSRF_COOKIE_NAME`). */
    name?: string;
    /** The `Path` attribute. Default `/`. */
    path?: string;
    /** The `Max-Age` attribute, in seconds. Omitted (session cookie) if not set. */
    maxAge?: number;
    /** The `SameSite` attribute. Default `Lax`. */
    sameSite?: "Strict" | "Lax" | "None";
    /** Set to `false` to omit the `Secure` (HTTPS-only) attribute — only for plain-HTTP local dev. Default `true`. */
    secure?: boolean;
}

/**
 * Issues and clears the double-submit CSRF cookie described in `@rapidrest/service-core`'s
 * `src/http/csrf/csrf.ts` (see that module's doc comment for the full design, including why this
 * cookie is deliberately host-only even though the sibling `jwt`/`refresh` cookies `TokenUtils` issues
 * are commonly wildcard-domain for SSO). `TokenUtils.createAuthResult()` calls `issueToken()` right
 * alongside writing the `jwt`/`refresh` cookies, and `TokenUtils.clearToken()` calls `clearToken()`
 * alongside clearing them, so a fresh CSRF token is minted at every login/refresh/elevation and
 * removed at logout — the same lifecycle as the session it protects.
 *
 * The token itself is generated by `@rapidrest/service-core`'s `generateCsrfToken()`
 * (`crypto.randomBytes(32).toString("base64url")`), matching the random-token style `OIDCStrategy`
 * already uses for its own `state` CSRF token.
 *
 * @author Jean-Philippe Steinmetz
 */
export class CsrfUtils {
    @Config("auth:csrf", { enabled: false, name: DEFAULT_CSRF_COOKIE_NAME })
    protected csrfConfig: CsrfCookieConfig = { enabled: false, name: DEFAULT_CSRF_COOKIE_NAME };

    /**
     * Generates a fresh CSRF token and writes it as a `Set-Cookie` header, when cookie issuance is
     * enabled via `auth:csrf.enabled`. No-op (and no cookie written) when `res` is omitted or disabled.
     *
     * @param res The response to write the `Set-Cookie` header to.
     */
    public issueToken(res?: HttpResponse): void {
        if (!res || !this.csrfConfig?.enabled) {
            return;
        }
        const token = generateCsrfToken();
        res.appendHeader(
            "Set-Cookie",
            buildCsrfCookie(token, {
                name: this.csrfConfig.name,
                path: this.csrfConfig.path,
                maxAge: this.csrfConfig.maxAge,
                sameSite: this.csrfConfig.sameSite,
                secure: this.csrfConfig.secure,
            }),
        );
    }

    /**
     * Clears the CSRF cookie previously written by `issueToken()`, when cookie issuance is enabled via
     * `auth:csrf.enabled`. Mirrors `TokenUtils.clearToken()`'s own clearing convention — called from
     * `BaseAuthLogoutRoute` alongside it.
     *
     * @param res The response to write the clearing `Set-Cookie` header to.
     */
    public clearToken(res?: HttpResponse): void {
        if (!res || !this.csrfConfig?.enabled) {
            return;
        }
        res.appendHeader(
            "Set-Cookie",
            buildCsrfCookie("", {
                name: this.csrfConfig.name,
                path: this.csrfConfig.path,
                sameSite: this.csrfConfig.sameSite,
                secure: this.csrfConfig.secure,
            }),
        );
    }
}
